Update sonar_buildspec.yml

diff --git a/aws-files/sonar_buildspec.yml b/aws-files/sonar_buildspec.yml
--- a/aws-files/sonar_buildspec.yml
+++ b/aws-files/sonar_buildspec.yml
@@ -1,37 +1,50 @@
 version: 0.2
+
 env:
   parameter-store:
-    LOGIN: LOGIN
-    HOST: HOST
-    Organization: Organization
-    Project: Project
-    #CODEARTIFACT_AUTH_TOKEN: CODEARTIFACT_AUTH_TOKEN
+    LOGIN: sonartoken
+    HOST: Host
+    ORGANISATION: Organisation
+    PROJECT: Project
+    CODEARTIFACT_AUTH_TOKEN: codeartifact-token
+
 phases:
   install:
     runtime-versions:
       java: corretto17
     commands:
-    - cp ./settings.xml /root/.m2/settings.xml
-    - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain ArtifactDomain --domain-owner ID --region REGION --query authorizationToken --output text`
+      - mkdir -p /root/.m2
+      - cp ./settings.xml /root/.m2/settings.xml
+      - export MAVEN_VERSION=3.9.10
+
   pre_build:
     commands:
       - apt-get update
-      - apt-get install -y jq checkstyle
-      - wget https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz
-      - tar xzvf apache-maven-3.9.4-bin.tar.gz
-      - ln -s apache-maven-3.9.4 maven
+      - apt-get install -y jq checkstyle unzip curl openjdk-17-jdk
+      - wget https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
+      - tar xzvf apache-maven-${MAVEN_VERSION}-bin.tar.gz
+      - ln -s apache-maven-${MAVEN_VERSION} maven
+      - export PATH=$PWD/maven/bin:$PATH
       - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
-      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
-      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
+      - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
+      - export PATH=$PATH:$PWD/sonar-scanner-3.3.0.1492-linux/bin
+      - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
+
   build:
     commands:
       - mvn test
       - mvn checkstyle:checkstyle
-      - echo "Installing JDK17 as its a dependency for sonarqube code analysis"
-      - apt-get install -y openjdk-17-jdk
-      - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
-      - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ -Dsonar.junit.reportsPath=target/surefire-reports/ -Dsonar.jacoco.reportsPath=target/jacoco.exec -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
+      - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$PROJECT -Dsonar.organization=$ORGANISATION -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ -Dsonar.junit.reportsPath=target/surefire-reports/ -Dsonar.jacoco.reportsPath=target/jacoco.exec -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
       - sleep 5
-      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
+      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECT > result.json
       - cat result.json
-      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
+      - |
+        if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
+          echo "Quality gate failed"
+          exit 1
+        fi
+
+artifacts:
+  files:
+    - target/**/*.war
+  discard-paths: yes
